### ISSUE TITLE
[Client] 서버쪽 API refactoring에 따른 API연동 코드 수정

### ISSUE THREAD

**Issue by hyeonjeongchung** [codestates/medisharp-client#119]
### ISSUE
- Group:  `client`
- Type: `fix`
- Detail: 서버쪽 API refactoring에 따른 API연동 코드 수정

### TODO
1. [x] Home Screen API 통신 단일화
2. [x] Calendar Screen API 통신 단일화
3. [ ] 일정등록 관련 API 통신 단일화  -> 진행중 @hyunju-song 

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__4__`
- Urgency: `Middle`
