### ISSUE TITLE
[Client] 약 상세 페이지 구현

### ISSUE THREAD

**Issue by hyunju-song** [codestates/medisharp-client#12]
### ISSUE
- Group:  `client`
- Type:  `feature`
- Detail: 약 상세 페이지 구현

### TODO
1. [x] 각 약들 클릭하면 상세페이지(issue #12)로 랜딩(카메라 인식 약/직접입력 약 구분)   
  약상세 페이지로 이동할때 클릭한 id, 약이름,카메라 인식 여부를 props를 페이지 이동 시 전달
2. [x] 약삭제 버튼 구현하기(슬라이드 혹은 클릭)
3. [x] Get My Medicine Info API 연동 후 받아온 res 기준으로 페이지 구현하기 
4. [x] &nbsp;&nbsp; a. Get My Medicine_camera_info -> Get My Medicine Info API의  if camera true인 경우로 바뀜
5. [x] &nbsp;&nbsp; b. Get My Medicine_write_info-> Get My Medicine Info API의  if camera false인 경우로 바뀜
6. [x]  약 삭제 API연동
~~7. [ ]  직접입력한 약 상세페이지 -> 약 정보 수정 API 연동~~ => 약 수정 page가 아직 만들어지지 않아서 구현 보류

### Estimated time
> #### `3h`

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Urgency:  `Middle`
