### ISSUE TITLE
[Client] Main_status page 구현

### ISSUE THREAD

**Issue by hyunju-song** [codestates/medisharp-client#4]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Main_status page 구현

### TODO
1. [x] Get Today Checked API
2. [x] 일주일간의 메시지 보여주기
3. [x] Get Alarms List API
4. [x] 오늘의 알람 리스트 보여주기 
5. [x] 상단 카운트다운 타이머 보여주기
5. [x] CSS

### Estimated time
> #### `2h`

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Urgency:  `Middle`
