### ISSUE TITLE
[Client] 복용현황페이지_내 일정 구현(res적용)

### ISSUE THREAD

**Issue by hyunju-song** [codestates/medisharp-client#7]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 복용현황페이지_내 일정 구현(res적용)

### TODO
0. [x] Get Monthly Checked
1. [x] 복용현황페이지_내 일정 구현(res적용)
2. [x] 날짜기준 CSS 분기
3. [x] 복용기준 CSS 분기
4. [x] 기본적으로 오늘 날짜에 선택되어있도록
5. [x] 하단에 오늘 날짜 알람리스트 보여주기

### Estimated time
> #### `3h`

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Urgency:  `Middle`
