### ISSUE TITLE
[Client] 알람등록페이지_약올리기 버튼/페이지 구현

### ISSUE THREAD

**Issue by hyunju-song** [codestates/medisharp-client#9]
### ISSUE
- Group:  `client`
- Type:  `feature`
- Detail: 알람등록페이지_약올리기 버튼/페이지 구현

### TODO
1. [x] 알람등록 페이지에서 약올리기 버튼 구현
2. [x] 약올리기 버튼 클릭 시, 안내페이지 구현
~~3. [ ] 카메라 촬영 버튼 클릭 시, 안내페이지 구현~~ 
4. [x] 카메라 하드웨어 접근
5. [x] 촬영된 이미지 서버로 보내기
6. [x] 서버에서 보내온 데이터 기반으로 약 정보 일치 문의 페이지 (예 / 아니오)
7. [x] 약정보 일치할 시, 추가 props 생성해서 일정 등록 페이지로 redirect 
8. [x] 불일치할 시, 직접입력 안내 페이지 이동 -> 직접 입력 페이지 이동
9. [x] 직접입력 페이지 구현 
10. [x] 사용자가 입력한 약정보 props 가지고 일정등록 페이지로 redirect @Gracechung-sw 
11. [x] 일정등록 버튼 클릭 시에 4개 API 실행될 수 있도록  
 Post Medicine   
 Post Schedules Common   
 Post Schedules Date   
 Post Schedules_common_medicine   
12. [x] post mediImg API를 이벤트에 할당하고, 로딩창을 구현하는 방법 고민 및 코드 수정

>ex)
```
POST req :
{
일정이름 : 일정
, 시간 : 시간
,시작일자 : 시작
,종료일자 : 종료
,주기 : 주기
,약정보 : [{약이름A,T}, {약이름C,T}] -> c
, 약정보B : [ {약이름B, 약정보들}] -> w
}
```

### Estimated time
> #### `3h`

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Urgency:  `Middle`
